In [27]:
import pandas as pd
import requests

In [28]:

lat = "52.52"
lon = "13.24"
API_key = "4a41e05edfedb3ef370a693a616136c0"  # Replace with the correct API key

url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}&units=metric"

response = requests.get(url)
weather_json = response.json()
weather_json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1743076800,
   'main': {'temp': 10.51,
    'feels_like': 9.39,
    'temp_min': 10.51,
    'temp_max': 13.38,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1015,
    'humidity': 68,
    'temp_kf': -2.87},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 29},
   'wind': {'speed': 2.3, 'deg': 285, 'gust': 2.6},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-27 12:00:00'},
  {'dt': 1743087600,
   'main': {'temp': 11.82,
    'feels_like': 10.6,
    'temp_min': 11.82,
    'temp_max': 14.45,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1013,
    'humidity': 59,
    'temp_kf': -2.63},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 21},
   'wind': {'speed': 2.21, 'deg': 287, 'gust': 2.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-27 15:00:00'},
  {'dt': 1743098400,
   'main': {'temp': 10.71,
    'feels_like': 9.4,
    'temp_min': 10.71,
    'temp_max': 10.81,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1013,
    'humidity': 60,
    'temp_kf': -0.1},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 12},
   'wind': {'speed': 1.28, 'deg': 301, 'gust': 1.26},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-27 18:00:00'},
  {'dt': 1743109200,
   'main': {'temp': 8.9,
    'feels_like': 8.52,
    'temp_min': 8.9,
    'temp_max': 8.9,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1013,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 58},
   'wind': {'speed': 1.39, 'deg': 243, 'gust': 1.4},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-27 21:00:00'},
  {'dt': 1743120000,
   'main': {'temp': 7.31,
    'feels_like': 6.29,
    'temp_min': 7.31,
    'temp_max': 7.31,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1013,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 35},
   'wind': {'speed': 1.76, 'deg': 218, 'gust': 1.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-28 00:00:00'},
  {'dt': 1743130800,
   'main': {'temp': 6.13,
    'feels_like': 5.06,
    'temp_min': 6.13,
    'temp_max': 6.13,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1012,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 4},
   'wind': {'speed': 1.65, 'deg': 197, 'gust': 1.7},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-28 03:00:00'},
  {'dt': 1743141600,
   'main': {'temp': 6.55,
    'feels_like': 5.35,
    'temp_min': 6.55,
    'temp_max': 6.55,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1011,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 4},
   'wind': {'speed': 1.82, 'deg': 176, 'gust': 3.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-28 06:00:00'},
  {'dt': 1743152400,
   'main': {'temp': 12.13,
    'feels_like': 10.78,
    'temp_min': 12.13,
    'temp_max': 12.13,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 53,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.65, 'deg': 168, 'gust': 3.94},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-28 09:00:00'},
  {'dt': 1743163200,
   'main': {'temp': 15.9,
    'feels_like': 14.56,
    'temp_min': 15.9,
    'temp_max': 15.9,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.01, 'deg': 157, 'gust': 3.99},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-28 12:00:00'},
  {'dt': 1743174000,
   'main': {'temp': 16.76,
    'feels_like': 15.43,
    'temp_min': 16.76,
    'temp_max': 16.76,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 36,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 3.01, 'deg': 141, 'gust': 3.81},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-28 15:00:00'},
  {'dt': 1743184800,
   'main': {'temp': 13.04,
    'feels_like': 11.63,
    'temp_min': 13.04,
    'temp_max': 13.04,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 47,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.54, 'deg': 132, 'gust': 5.72},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-28 18:00:00'},
  {'dt': 1743195600,
   'main': {'temp': 10.54,
    'feels_like': 9.14,
    'temp_min': 10.54,
    'temp_max': 10.54,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 17},
   'wind': {'speed': 2.86, 'deg': 124, 'gust': 7.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-28 21:00:00'},
  {'dt': 1743206400,
   'main': {'temp': 8.79,
    'feels_like': 7.62,
    'temp_min': 8.79,
    'temp_max': 8.79,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1003,
    'humidity': 64,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 26},
   'wind': {'speed': 2.19, 'deg': 101, 'gust': 4.39},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-29 00:00:00'},
  {'dt': 1743217200,
   'main': {'temp': 7.81,
    'feels_like': 6.61,
    'temp_min': 7.81,
    'temp_max': 7.81,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1003,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.03, 'deg': 67, 'gust': 3.76},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-29 03:00:00'},
  {'dt': 1743228000,
   'main': {'temp': 8.04,
    'feels_like': 6.9,
    'temp_min': 8.04,
    'temp_max': 8.04,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 1004,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.01, 'deg': 20, 'gust': 3.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-29 06:00:00'},
  {'dt': 1743238800,
   'main': {'temp': 12.08,
    'feels_like': 10.73,
    'temp_min': 12.08,
    'temp_max': 12.08,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 53,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.94, 'deg': 9, 'gust': 4.12},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-29 09:00:00'},
  {'dt': 1743249600,
   'main': {'temp': 14.53,
    'feels_like': 13.24,
    'temp_min': 14.53,
    'temp_max': 14.53,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 46,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.25, 'deg': 349, 'gust': 5.11},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-29 12:00:00'},
  {'dt': 1743260400,
   'main': {'temp': 13.87,
    'feels_like': 12.83,
    'temp_min': 13.87,
    'temp_max': 13.87,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.67, 'deg': 341, 'gust': 6.75},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-29 15:00:00'},
  {'dt': 1743271200,
   'main': {'temp': 9.24,
    'feels_like': 6.46,
    'temp_min': 9.24,
    'temp_max': 9.24,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1011,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.48, 'deg': 337, 'gust': 10.52},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-29 18:00:00'},
  {'dt': 1743282000,
   'main': {'temp': 7.23,
    'feels_like': 4.58,
    'temp_min': 7.23,
    'temp_max': 7.23,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1012,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 90},
   'wind': {'speed': 4.03, 'deg': 328, 'gust': 10.48},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-29 21:00:00'},
  {'dt': 1743292800,
   'main': {'temp': 5.29,
    'feels_like': 2.31,
    'temp_min': 5.29,
    'temp_max': 5.29,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1013,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 74},
   'wind': {'speed': 3.84, 'deg': 313, 'gust': 10.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-30 00:00:00'},
  {'dt': 1743303600,
   'main': {'temp': 3.63,
    'feels_like': 0.72,
    'temp_min': 3.63,
    'temp_max': 3.63,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1013,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 3.18, 'deg': 302, 'gust': 8.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-30 03:00:00'},
  {'dt': 1743314400,
   'main': {'temp': 3.16,
    'feels_like': 0.1,
    'temp_min': 3.16,
    'temp_max': 3.16,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 1013,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 4},
   'wind': {'speed': 3.25, 'deg': 291, 'gust': 6.81},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-30 06:00:00'},
  {'dt': 1743325200,
   'main': {'temp': 8.15,
    'feels_like': 5.91,
    'temp_min': 8.15,
    'temp_max': 8.15,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 1013,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 40},
   'wind': {'speed': 3.65, 'deg': 277, 'gust': 5.33},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-30 09:00:00'},
  {'dt': 1743336000,
   'main': {'temp': 8.36,
    'feels_like': 6.31,
    'temp_min': 8.36,
    'temp_max': 8.36,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1011,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 70},
   'wind': {'speed': 3.38, 'deg': 249, 'gust': 5.57},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.25},
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-30 12:00:00'},
  {'dt': 1743346800,
   'main': {'temp': 8.44,
    'feels_like': 5.16,
    'temp_min': 8.44,
    'temp_max': 8.44,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 6.31, 'deg': 265, 'gust': 8.53},
   'visibility': 10000,
   'pop': 0.21,
   'rain': {'3h': 0.13},
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-30 15:00:00'},
  {'dt': 1743357600,
   'main': {'temp': 5.92,
    'feels_like': 3.41,
    'temp_min': 5.92,
    'temp_max': 5.92,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.29, 'deg': 261, 'gust': 5.99},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 1.56},
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-30 18:00:00'},
  {'dt': 1743368400,
   'main': {'temp': 6.2,
    'feels_like': 4.85,
    'temp_min': 6.2,
    'temp_max': 6.2,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.92, 'deg': 296, 'gust': 4},
   'visibility': 10000,
   'pop': 0.97,
   'rain': {'3h': 0.55},
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-30 21:00:00'},
  {'dt': 1743379200,
   'main': {'temp': 6.09,
    'feels_like': 4.99,
    'temp_min': 6.09,
    'temp_max': 6.09,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 1012,
    'humidity': 91,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.67, 'deg': 4, 'gust': 3.56},
   'visibility': 10000,
   'pop': 0.53,
   'rain': {'3h': 0.12},
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-31 00:00:00'},
  {'dt': 1743390000,
   'main': {'temp': 6.04,
    'feels_like': 4.42,
    'temp_min': 6.04,
    'temp_max': 6.04,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 1014,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.17, 'deg': 44, 'gust': 4.94},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.12},
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-31 03:00:00'},
  {'dt': 1743400800,
   'main': {'temp': 5.66,
    'feels_like': 3.61,
    'temp_min': 5.66,
    'temp_max': 5.66,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1017,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 91},
   'wind': {'speed': 2.59, 'deg': 50, 'gust': 5.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-31 06:00:00'},
  {'dt': 1743411600,
   'main': {'temp': 9.28,
    'feels_like': 7.7,
    'temp_min': 9.28,
    'temp_max': 9.28,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1020,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 20},
   'wind': {'speed': 2.91, 'deg': 39, 'gust': 3.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-31 09:00:00'},
  {'dt': 1743422400,
   'main': {'temp': 10.56,
    'feels_like': 9,
    'temp_min': 10.56,
    'temp_max': 10.56,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 51,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 40},
   'wind': {'speed': 3.49, 'deg': 7, 'gust': 3.53},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-31 12:00:00'},
  {'dt': 1743433200,
   'main': {'temp': 10.68,
    'feels_like': 9.11,
    'temp_min': 10.68,
    'temp_max': 10.68,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 98},
   'wind': {'speed': 3.73, 'deg': 353, 'gust': 3.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2025-03-31 15:00:00'},
  {'dt': 1743444000,
   'main': {'temp': 8.17,
    'feels_like': 6.54,
    'temp_min': 8.17,
    'temp_max': 8.17,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 65},
   'wind': {'speed': 2.66, 'deg': 353, 'gust': 5.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-31 18:00:00'},
  {'dt': 1743454800,
   'main': {'temp': 5.61,
    'feels_like': 3.57,
    'temp_min': 5.61,
    'temp_max': 5.61,
    'pressure': 1030,
    'sea_level': 1030,
    'grnd_level': 1024,
    'humidity': 71,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 7},
   'wind': {'speed': 2.56, 'deg': 24, 'gust': 6.09},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-03-31 21:00:00'},
  {'dt': 1743465600,
   'main': {'temp': 3.83,
    'feels_like': 1.39,
    'temp_min': 3.83,
    'temp_max': 3.83,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1024,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 2.64, 'deg': 23, 'gust': 6.68},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-04-01 00:00:00'},
  {'dt': 1743476400,
   'main': {'temp': 2.85,
    'feels_like': 0.24,
    'temp_min': 2.85,
    'temp_max': 2.85,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1024,
    'humidity': 74,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.63, 'deg': 26, 'gust': 7.7},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2025-04-01 03:00:00'},
  {'dt': 1743487200,
   'main': {'temp': 3.85,
    'feels_like': 1.02,
    'temp_min': 3.85,
    'temp_max': 3.85,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1024,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 3.14, 'deg': 35, 'gust': 9.04},
   'visibility': 10000,
   'pop': 0,

In [29]:
weather_json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [42]:
from datetime import datetime
tz = 'Europe/Berlin'
from pytz import timezone
datetime.now(timezone(tz))

datetime.datetime(2025, 3, 27, 11, 47, 43, 958364, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)

In [45]:
data = {
    'city':[],
    'date':[],
    'temperature':[],
    'feels_like':[],
    'wind_speed':[],
    'visibility':[],
    'rain':[],
    'snow':[],
    'time_retrieved': []
}

In [37]:
records = []
for time_window in weather_json['list']:
    records.append({
    
        'date': time_window['dt_txt'],
        'temperature': time_window['main'].get('temp', None),
        'feels_like': time_window['main'].get('feels_like', None),
        'wind_speed': time_window['wind'].get('speed', None),
        'visibility': time_window.get('visibility', None),
        'rain': time_window.get('rain', {}).get('3h', None),
        'snow': time_window.get('snow', {}).get('3h', None),
        'time_retrieved': datetime.now(timezone("Europe/Berlin"))
    })

In [38]:
weather_df = pd.DataFrame(records)
weather_df

,date,temperature,feels_like,wind_speed,visibility,rain,snow,time_retrieved
0,2025-03-27 12:00:00,10.51,9.39,2.30,10000,NaN,None,2025-03-27 11:42:39.820371+01:00
1,2025-03-27 15:00:00,11.82,10.60,2.21,10000,NaN,None,2025-03-27 11:42:39.820395+01:00
2,2025-03-27 18:00:00,10.71,9.40,1.28,10000,NaN,None,2025-03-27 11:42:39.820401+01:00
3,2025-03-27 21:00:00,8.90,8.52,1.39,10000,NaN,None,2025-03-27 11:42:39.820407+01:00
4,2025-03-28 00:00:00,7.31,6.29,1.76,10000,NaN,None,2025-03-27 11:42:39.820412+01:00
5,2025-03-28 03:00:00,6.13,5.06,1.65,10000,NaN,None,2025-03-27 11:42:39.820415+01:00
6,2025-03-28 06:00:00,6.55,5.35,1.82,10000,NaN,None,2025-03-27 11:42:39.820419+01:00
7,2025-03-28 09:00:00,12.13,10.78,2.65,10000,NaN,None,2025-03-27 11:42:39.820422+01:00
8,2025-03-28 12:00:00,15.90,14.56,3.01,10000,NaN,None,2025-03-27 11:42:39.820427+01:00
9,2025-03-28 15:00:00,16.76,15.43,3.01,10000,NaN,None,2025-03-27 11:42:39.820431+01:00
10,2025-03-28 18:00:00,13.04,11.63,2.54,10000,NaN,None,2025-03-27 11:42:39.820435+01:00
11,2025-03-28 21:00:00,10.54,9.14,2.86,10000,NaN,None,2025-03-27 11:42:39.820440+01:00
12,2025-03-29 00:00:00,8.79,7.62,2.19,10000,NaN,None,2025-03-27 11:42:39.820445+01:00
13,2025-03-29 03:00:00,7.81,6.61,2.03,10000,NaN,None,2025-03-27 11:42:39.820449+01:00
14,2025-03-29 06:00:00,8.04,6.90,2.01,10000,NaN,None,2025-03-27 11:42:39.820453+01:00
15,2025-03-29 09:00:00,12.08,10.73,2.94,10000,NaN,None,2025-03-27 11:42:39.820457+01:00
16,2025-03-29 12:00:00,14.53,13.24,4.25,10000,NaN,None,2025-03-27 11:42:39.820461+01:00
17,2025-03-29 15:00:00,13.87,12.83,5.67,10000,NaN,None,2025-03-27 11:42:39.820464+01:00
18,2025-03-29 18:00:00,9.24,6.46,5.48,10000,NaN,None,2025-03-27 11:42:39.820469+01:00
19,2025-03-29 21:00:00,7.23,4.58,4.03,10000,NaN,None,2025-03-27 11:42:39.820473+01:00
20,2025-03-30 00:00:00,5.29,2.31,3.84,10000,NaN,None,2025-03-27 11:42:39.820478+01:00
21,2025-03-30 03:00:00,3.63,0.72,3.18,10000,NaN,None,2025-03-27 11:42:39.820482+01:00
22,2025-03-30 06:00:00,3.16,0.10,3.25,10000,NaN,None,2025-03-27 11:42:39.820486+01:00
23,2025-03-30 09:00:00,8.15,5.91,3.65,10000,NaN,None,2025-03-27 11:42:39.820490+01:00
24,2025-03-30 12:00:00,8.36,6.31,3.38,10000,0.25,None,2025-03-27 11:42:39.820495+01:00
25,2025-03-30 15:00:00,8.44,5.16,6.31,10000,0.13,None,2025-03-27 11:42:39.820500+01:00
26,2025-03-30 18:00:00,5.92,3.41,3.29,10000,1.56,None,2025-03-27 11:42:39.820504+01:00
27,2025-03-30 21:00:00,6.20,4.85,1.92,10000,0.55,None,2025-03-27 11:42:39.820509+01:00
28,2025-03-31 00:00:00,6.09,4.99,1.67,10000,0.12,None,2025-03-27 11:42:39.820514+01:00
29,2025-03-31 03:00:00,6.04,4.42,2.17,10000,0.12,None,2025-03-27 11:42:39.820519+01:00
30,2025-03-31 06:00:00,5.66,3.61,2.59,10000,NaN,None,2025-03-27 11:42:39.820523+01:00
31,2025-03-31 09:00:00,9.28,7.70,2.91,10000,NaN,None,2025-03-27 11:42:39.820527+01:00
32,2025-03-31 12:00:00,10.56,9.00,3.49,10000,NaN,None,2025-03-27 11:42:39.820532+01:00
33,2025-03-31 15:00:00,10.68,9.11,3.73,10000,NaN,None,2025-03-27 11:42:39.820537+01:00
34,2025-03-31 18:00:00,8.17,6.54,2.66,10000,NaN,None,2025-03-27 11:42:39.820543+01:00
35,2025-03-31 21:00:00,5.61,3.57,2.56,10000,NaN,None,2025-03-27 11:42:39.820549+01:00
36,2025-04-01 00:00:00,3.83,1.39,2.64,10000,NaN,None,2025-03-27 11:42:39.820554+01:00
37,2025-04-01 03:00:00,2.85,0.24,2.63,10000,NaN,None,2025-03-27 11:42:39.820559+01:00
38,2025-04-01 06:00:00,3.85,1.02,3.14,10000,NaN,None,2025-03-27 11:42:39.820563+01:00
39,2025-04-01 09:00:00,10.33,8.54,3.93,10000,NaN,None,2025-03-27 11:42:39.820567+01:00

In [73]:
cities = ['Berlin','New York City','London','Paris','Munich','Rome','Paris','Tabriz','Ottawa','Cairo','Bogota']
api_key = "d2cb9aca244a309b24e15ee4f523c61a"  # Replace with a valid API key

In [74]:
for city in cities:
    geo_url = f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={api_key}'
    geo_response = requests.get(geo_url)
    geo_json = geo_response.json()

    if geo_json:
        lat = geo_json[0]['lat']
        lon = geo_json[0]['lon']

        url = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}&units=metric'
        weather_response = requests.get(url)
        weather_json = weather_response.json()

        for time_window in weather_json['list']:
            data['city'].append(city)
            data['date'].append(time_window['dt_txt'])
            data['temperature'].append(time_window['main'].get('temp', None))
            data['feels_like'].append(time_window['main'].get('feels_like', None))
            data['wind_speed'].append(time_window['wind'].get('speed', None))
            data['visibility'].append(time_window.get('visibility', None))
            data['rain'].append(time_window.get('rain', {}).get('3h', None))
            data['snow'].append(time_window.get('snow', {}).get('3h', None))
            data['time_retrieved'].append(datetime.now(timezone(tz)))

In [76]:
City_weather= pd.DataFrame(data)
City_weather

,city,date,temperature,feels_like,wind_speed,visibility,rain,snow,time_retrieved
0,Ottawa,2025-03-27 12:00:00,-4.59,-8.12,2.23,10000.0,NaN,NaN,2025-03-27 11:51:09.422974+01:00
1,Ottawa,2025-03-27 15:00:00,-2.41,-6.82,3.47,10000.0,NaN,NaN,2025-03-27 11:51:09.423010+01:00
2,Ottawa,2025-03-27 18:00:00,2.56,-1.84,5.24,10000.0,NaN,NaN,2025-03-27 11:51:09.423017+01:00
3,Ottawa,2025-03-27 21:00:00,6.92,3.44,5.73,10000.0,NaN,NaN,2025-03-27 11:51:09.423023+01:00
4,Ottawa,2025-03-28 00:00:00,3.18,-1.21,5.56,10000.0,NaN,0.25,2025-03-27 11:51:09.423028+01:00
...,...,...,...,...,...,...,...,...,...
675,Bogota,2025-03-31 21:00:00,14.37,14.24,1.08,10000.0,3.21,NaN,2025-03-27 12:35:18.176188+01:00
676,Bogota,2025-04-01 00:00:00,12.74,12.55,0.71,10000.0,2.00,NaN,2025-03-27 12:35:18.176190+01:00
677,Bogota,2025-04-01 03:00:00,12.76,12.57,0.75,5314.0,2.10,NaN,2025-03-27 12:35:18.176192+01:00
678,Bogota,2025-04-01 06:00:00,11.97,11.73,0.58,10000.0,1.26,NaN,2025-03-27 12:35:18.176194+01:00
679,Bogota,2025-04-01 09:00:00,11.68,11.41,0.28,10000.0,0.78,NaN,2025-03-27 12:35:18.176196+01:00

In [77]:
schema = "sql_workshop"
host = "127.0.0.1"
user = "root"
password = "saNAY=2010"
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [78]:
from sqlalchemy import create_engine

engine = create_engine(connection_string)

In [79]:
city_ids = pd.read_sql("SELECT city_id, city_name FROM Static_cities", con=engine)
city_map = dict(zip(city_ids['city_name'], city_ids['city_id']))

In [80]:
City_weather['city_id'] = City_weather['city'].map(city_map)
City_weather

,city,date,temperature,feels_like,wind_speed,visibility,rain,snow,time_retrieved,city_id
0,Ottawa,2025-03-27 12:00:00,-4.59,-8.12,2.23,10000.0,NaN,NaN,2025-03-27 11:51:09.422974+01:00,9.0
1,Ottawa,2025-03-27 15:00:00,-2.41,-6.82,3.47,10000.0,NaN,NaN,2025-03-27 11:51:09.423010+01:00,9.0
2,Ottawa,2025-03-27 18:00:00,2.56,-1.84,5.24,10000.0,NaN,NaN,2025-03-27 11:51:09.423017+01:00,9.0
3,Ottawa,2025-03-27 21:00:00,6.92,3.44,5.73,10000.0,NaN,NaN,2025-03-27 11:51:09.423023+01:00,9.0
4,Ottawa,2025-03-28 00:00:00,3.18,-1.21,5.56,10000.0,NaN,0.25,2025-03-27 11:51:09.423028+01:00,9.0
...,...,...,...,...,...,...,...,...,...,...
675,Bogota,2025-03-31 21:00:00,14.37,14.24,1.08,10000.0,3.21,NaN,2025-03-27 12:35:18.176188+01:00,11.0
676,Bogota,2025-04-01 00:00:00,12.74,12.55,0.71,10000.0,2.00,NaN,2025-03-27 12:35:18.176190+01:00,11.0
677,Bogota,2025-04-01 03:00:00,12.76,12.57,0.75,5314.0,2.10,NaN,2025-03-27 12:35:18.176192+01:00,11.0
678,Bogota,2025-04-01 06:00:00,11.97,11.73,0.58,10000.0,1.26,NaN,2025-03-27 12:35:18.176194+01:00,11.0
679,Bogota,2025-04-01 09:00:00,11.68,11.41,0.28,10000.0,0.78,NaN,2025-03-27 12:35:18.176196+01:00,11.0

In [81]:
print(city_map)

{'Berlin': 1, 'New York City': 2, 'London': 3, 'Paris': 7, 'Munich': 5, 'Rome': 6, 'Tabriz': 8, 'Ottawa': 9, 'Cairo': 10, 'Bogota': 11}

In [82]:
print(City_weather[['city', 'city_id']])

       city  city_id
0    Ottawa      9.0
1    Ottawa      9.0
2    Ottawa      9.0
3    Ottawa      9.0
4    Ottawa      9.0
..      ...      ...
675  Bogota     11.0
676  Bogota     11.0
677  Bogota     11.0
678  Bogota     11.0
679  Bogota     11.0

[680 rows x 2 columns]

In [83]:
City_weather = City_weather.dropna(subset=['city_id'])
City_weather['city_id'] = City_weather['city_id'].astype(int)

C:\Users\esmae\AppData\Local\Temp\ipykernel_12496\2765779004.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  City_weather['city_id'] = City_weather['city_id'].astype(int)

In [84]:
columns_to_insert = [
    'city_id',
    'date',
    'time_retrieved',
    'temperature',
    'feels_like',
    'wind_speed',
    'visibility',
    'rain',
    'snow'
]

data_to_insert = City_weather[columns_to_insert]

In [88]:
data_to_insert.to_sql('Weather', con=engine, if_exists='append', index=False)

C:\Users\esmae\AppData\Local\Temp\ipykernel_12496\3959610082.py:1: UserWarning: The provided table name 'Weather' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  data_to_insert.to_sql('Weather', con=engine, if_exists='append', index=False)

560